'use strict';
(()=>{
const L=window.ROZA_LIBRARY,C=window.ROZA_CAMPAIGN,B=window.ROZA_BRAND_STRATEGY,E=window.ROZA_EVIDENCE;
if(!L?.records?.length)return;
const $=s=>document.querySelector(s),all=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=v=>Array.isArray(v)?v:v?[v]:[];
const text=v=>typeof v==='string'?v:Array.isArray(v)?v.map(text).join('\n'):v&&typeof v==='object'?Object.entries(v).map(([k,x])=>k.replace(/([a-z])([A-Z])/g,'$1 $2')+': '+text(x)).join('\n'):String(v??'');
const para=v=>'<p>'+esc(text(v)).replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>')+'</p>';
const safeUrl=u=>/^https:\/\//.test(String(u))?esc(u):'#';
const original=r=>'<a class="primary" href="'+safeUrl(r.url)+'" target="_blank" rel="noopener noreferrer">Open original '+(r.recordType==='Article'?'article':'post')+'</a>';
const section=(title,body)=>'<section class="detail-section"><h3>'+esc(title)+'</h3>'+body+'</section>';
const fact=(title,body)=>'<div class="fact"><dt>'+esc(title)+'</dt><dd>'+esc(body)+'</dd></div>';
const detail=(title,body)=>'<details><summary>'+esc(title)+'</summary><div>'+body+'</div></details>';
let view='references',planMode='list',context=null,postId=null,captionPlatform='linkedin';
const dialog=$('#detail-dialog');
const refBy=id=>L.records.find(r=>r.id===id),ideaBy=id=>B.heroConcepts.find(r=>r.id===id),postBy=id=>C.posts.find(r=>r.id===id);
function cleanLesson(s){return String(s||'').replace(/^(Observed|Interpretation):\s*/,'');}
function ideaLane(c){return c.id.startsWith('LAB')?'ROZA LAB':c.id.startsWith('HUBB')?'HUBB':'Spices';}
function refIdeas(id){return B.heroConcepts.filter(c=>c.sourceRefs.some(r=>r.id===id));}
function refPosts(id){return C.posts.filter(p=>p.sourceRefs.some(r=>r.id===id));}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),3600);}
function options(){const brands=view==='references'?[...new Set(L.records.map(r=>r.brand))].sort():view==='ideas'?['ROZA LAB','HUBB','Spices']:['B2B PROJECT','HUBB pilot'];$('#brand-filter').innerHTML='<option value="all">'+(view==='references'?'All source brands':view==='ideas'?'All brand lanes':'All audiences')+'</option>'+brands.map(x=>'<option>'+esc(x)+'</option>').join('');$('#brand-label').textContent=view==='references'?'Source brand':view==='ideas'?'Brand lane':'Audience';}
function setView(next,keepContext=false){if(!['references','ideas','plans'].includes(next))throw Error('Unknown view');view=next;if(!keepContext)context=null;$('#search').value='';$('#platform-filter').value='all';$('#format-filter').value='all';options();const copy={references:['YOUR RESEARCH SHELF','References worth opening.','See the original. Understand the idea. Find your own direction.'],ideas:['ORIGINAL DIRECTIONS','Turn a reference into your own idea.','Ten proposed directions, linked to the posts that informed them.'],plans:['PROPOSED OCTOBER PLAN','Ideas with a place in the plan.','16 draft post families. Dates are proposed; nothing is scheduled.']}[view];$('#view-kicker').textContent=copy[0];$('#view-title').textContent=copy[1];$('#view-description').textContent=copy[2];$('#platform-control').hidden=view==='ideas';$('#evidence-control').hidden=view!=='references';$('#format-control').hidden=view!=='plans';$('#plan-view-options').hidden=view!=='plans';all('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});render();return{view,readOnly:true};}
function filters(){return{search:$('#search').value.toLowerCase().trim(),brand:$('#brand-filter').value,platform:$('#platform-filter').value,evidence:$('#evidence-filter').value,format:$('#format-filter').value};}
function selected(){const f=filters();let rows=view==='references'?L.records:view==='ideas'?B.heroConcepts:C.posts;return rows.filter(r=>{
 if(f.search&&!text(view==='references'?[r.brand,r.title,r.why,r.observed,r.mechanism,r.lanes]:view==='ideas'?[r.title,r.objective,r.originalAdaptation,ideaLane(r)]:[r.title,r.hook,r.audience,r.copy]).toLowerCase().includes(f.search))return false;
 if(view==='references'){if(f.brand!=='all'&&r.brand!==f.brand)return false;if(f.platform!=='all'&&r.platform!==f.platform)return false;if(f.evidence==='captured'&&!r.images.length)return false;if(f.evidence==='textonly'&&r.images.length)return false;if(f.evidence==='live'&&!/^(?:Live|Actual live)\b/i.test(r.evidenceTier))return false;if(f.evidence==='cached'&&!r.evidenceTier.startsWith('Cached'))return false;if(f.evidence==='snippet'&&!r.evidenceTier.startsWith('Search'))return false;}
 else if(view==='ideas'){if(f.brand!=='all'&&ideaLane(r)!==f.brand)return false;if(context&&!r.sourceRefs.some(x=>x.id===context))return false;}
 else{if(f.brand!=='all'&&r.audience!==f.brand)return false;if(f.platform!=='all'&&!r.platforms.includes(f.platform))return false;if(f.format!=='all'&&r.primaryFormat!==f.format)return false;if(context&&!r.sourceRefs.some(x=>x.id===context))return false;}
 return true;
 });}
function referenceCard(r,index=0){const image=r.images[0];return'<article class="reference-card"><button class="card-open" data-open-ref="'+esc(r.id)+'" aria-label="Open '+esc(r.brand+': '+r.title)+'">'+(image?'<div class="source-visual"><img src="'+esc(image.src)+'" loading="'+(index<8?'eager':'lazy')+'" decoding="async" alt="'+esc(r.brand+' actual captured '+r.platform+' post excerpt')+'">'+(r.aiLabel?'<span class="ai-label">Publisher labels this AI content</span>':'')+'</div>':'<div class="text-reference"><b>'+esc(r.brand)+'</b><span>'+esc(r.evidenceTier)+' · no saved visual</span></div>')+'<div class="card-copy"><div class="card-meta"><span class="platform">'+esc(r.platform)+'</span><span>'+esc(r.id)+' · '+esc(r.sourceBase)+'</span></div><h2>'+esc(r.title)+'</h2><p class="card-brand">'+esc(r.brand)+'</p><p class="card-date">'+esc(r.publishedDate||r.publishedLabel||'Date unverified')+'</p><p class="card-lesson">'+esc(cleanLesson(r.why))+'</p></div></button><div class="card-bottom"><span class="status-chip">'+esc(r.images.length?'Visual available':r.evidenceTier==='Search snippet only'?'Snippet only':'Text only')+'</span><a href="'+safeUrl(r.url)+'" target="_blank" rel="noopener noreferrer" aria-label="Open original '+esc(r.brand)+' post">Original post</a></div></article>';}
function ideaCard(c){const lane=ideaLane(c),steps=lane==='HUBB'?'Shell / kernel / flavour':lane==='Spices'?'Dish / addition / tested finish':'Product / question / next decision';return'<article class="idea-card"><button class="card-open" data-open-idea="'+esc(c.id)+'"><div class="idea-cover '+(lane==='HUBB'?'hubb':lane==='Spices'?'spice':'')+'"><span>'+esc(lane)+' · '+esc(c.id)+'</span><b>'+esc(c.title)+'</b><span class="idea-steps">'+esc(steps)+'</span></div><div class="card-copy"><p class="card-lesson">'+esc(c.objective)+'</p></div></button><div class="card-bottom"><span class="status-chip">Proposed idea</span><span class="card-brand">'+c.sourceRefs.length+' references · '+c.sequence.length+' frames</span></div></article>';}
function planRow(p){const day=Number(p.date.slice(-2));return'<button class="plan-row" data-open-post="'+esc(p.id)+'"><span class="plan-date">OCT<strong>'+day+'</strong></span><span class="plan-title"><strong>'+esc(p.title)+'</strong><span>'+esc(p.id+' · '+p.audience+' · '+p.platforms.join(', '))+'</span></span><span class="plan-format">'+esc(p.primaryFormat)+'</span><span class="status-chip">Proposed draft</span></button>';}
function calendar(rows){let s='<div class="calendar">'+['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>'<div class="calendar-head">'+d+'</div>').join('');for(let i=0;i<3;i++)s+='<div class="calendar-day" aria-hidden="true"></div>';for(let d=1;d<=31;d++){const posts=rows.filter(p=>Number(p.date.slice(-2))===d);s+='<div class="calendar-day"><span>'+d+'</span>'+posts.map(p=>'<button data-open-post="'+esc(p.id)+'" aria-label="October '+d+', '+esc(p.title)+', proposed draft"><b>'+esc(p.primaryFormat)+'</b>'+esc(p.title)+'</button>').join('')+'</div>';}return s+'</div>';}
function render(){const rows=selected();const visualCount=L.records.filter(r=>r.images.length).length;const textCount=L.records.length-visualCount;$('#reference-nav-count').textContent=L.records.length;$('#evidence-note').textContent=L.records.length+' references · '+visualCount+' with captured post visuals · '+textCount+' text only · checked 3 October 2026. No example is verified as trending.';$('#results-count').textContent=view==='references'?rows.length+' shown · '+visualCount+' visual / '+textCount+' text-only references in the full library':view==='ideas'?rows.length+' original ideas · concepts awaiting real assets':rows.length+' proposed posts · October 2026';$('#context-filter').hidden=!context;$('#context-filter').innerHTML=context?'Related to '+esc(refBy(context)?.brand||context)+' <button id="clear-context">Show all</button>':'';if(context)$('#clear-context').addEventListener('click',()=>{context=null;render();});const r=$('#results');r.className=view==='references'?'reference-grid':view==='ideas'?'idea-grid':planMode==='list'?'plan-list':'';r.innerHTML=rows.length?(view==='references'?rows.sort((a,b)=>Number(!!b.images.length)-Number(!!a.images.length)).map(referenceCard).join(''):view==='ideas'?rows.map(ideaCard).join(''):planMode==='list'?rows.map(planRow).join(''):calendar(rows)):'<div class="empty-state"><h2>No matching '+esc(view)+'.</h2><p>Try a broader search or change a filter.</p><button class="secondary" id="reset-filters">Reset filters</button></div>';const reset=$('#reset-filters');if(reset)reset.addEventListener('click',()=>setView(view));bindOpeners(r);}
function showDrawer(type,title,body){$('#drawer-type').textContent=type;$('#drawer-title').textContent=title;$('#drawer-body').innerHTML=body;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;bindOpeners($('#drawer-body'));$('#close-dialog').focus();}
function refLinks(refs){return'<div class="detail-links">'+refs.map(r=>'<button class="detail-link" data-open-ref="'+esc(r.id)+'">'+esc(r.id+' · '+r.brand)+'</button>').join('')+'</div>';}
function relatedLinks(rows,type){return'<div class="detail-links">'+rows.map(r=>'<button class="detail-link" data-open-'+type+'="'+esc(r.id)+'">'+esc(r.title)+'<small>'+esc(r.id+(type==='post'?' · '+r.date:' · '+ideaLane(r)))+'</small></button>').join('')+'</div>';}
function pdfLinks(r){return E.meta.pdfAvailable&&r.pdfPages.length?'<div class="detail-links">'+r.pdfPages.map(p=>'<a href="'+esc(E.meta.pdfPath)+'#page='+p+'" target="_blank" rel="noopener noreferrer">Research PDF · p'+p+'</a>').join('')+'</div>':'';}
function openReference(id){const r=refBy(id);if(!r)throw Error('Unknown reference');const ideas=refIdeas(id),posts=refPosts(id);const media=r.images.length?'<figure class="evidence-image"><a href="'+esc(r.images[0].src)+'" target="_blank" rel="noopener noreferrer"><img src="'+esc(r.images[0].src)+'" alt="'+esc(r.brand+' actual post excerpt. '+r.images[0].notes)+'"></a><figcaption>'+esc(r.brand+' · '+r.platform+' · captured '+r.checkedAt)+'. Open the image to inspect it.</figcaption></figure>':'<div class="evidence-warning">No screenshot is saved for this record. The reference is based on '+esc(r.evidenceTier.toLowerCase())+'.</div>';
 const contextImages=r.images.slice(1).map(i=>'<figure class="context-image"><img src="'+esc(i.src)+'" alt="'+esc(i.notes)+'"><figcaption class="caption-note">'+esc(i.notes)+'</figcaption></figure>').join('');
 const metrics=Object.keys(r.metrics).length?Object.entries(r.metrics).map(([k,v])=>k+': '+v).join(' · '):'No usable engagement count recorded';
 const adaptation=ideas.length?relatedLinks(ideas,'idea'):para(r.adaptation||'No original adaptation has been drafted for this reference yet.');
 let body='<div class="drawer-actions">'+original(r)+'<span class="status-chip">'+esc(r.sourceBase+' · '+r.evidenceTier)+'</span></div>'+media+(r.sourceWarning?'<p class="evidence-warning">'+esc(r.sourceWarning)+'</p>':'')+(r.aiLabel?'<div class="evidence-warning"><b>Visible AI content label.</b> This is a genuine capture of a published post; the depicted visual is not verified as wholly photographic or documentary.</div>'+contextImages:contextImages?detail('Additional publisher / caption context',contextImages):'')+(r.limitedCreative?'<p class="evidence-warning">Partial creative only. The saved image does not show the complete post layout.</p>':'')+section('Why this was referenced',para(cleanLesson(r.why)))+section('Original directions to explore',adaptation)+(posts.length?section('Already connected to proposed posts',relatedLinks(posts,'post')):'')+detail('What was actually observed',para(r.observed)+para(r.format))+detail('Dates, evidence and performance limits','<dl class="detail-facts">'+fact('Published',r.publishedDate||r.publishedLabel||'Date unverified')+fact('Date evidence',r.dateEvidence||'Exact date unverified')+fact('Checked',r.checkedAt+' · snapshot, not live monitoring')+fact('Trend status','Trending not established')+fact('Visible engagement snapshot',metrics)+fact('Metrics observed',r.metricsAt||'Time not recorded')+'</dl>'+para('Reach, audience size, paid support, saves and comparative performance are not established unless specifically recorded. Visible counts are not evidence of a trend.')+para(r.limits)+pdfLinks(r))+section('Discuss or keep for a client plan','<p class="caption-note">Shared comments and saved client plans are not available in this read-only version. The original references and prepared adaptations remain available to open and copy.</p>');
 showDrawer(r.platform+' · '+r.brand+' · '+r.id,r.title,body);return{referenceId:id,readOnly:true};}
function openIdea(id){const c=ideaBy(id);if(!c)throw Error('Unknown idea');const sourceRefs=c.sourceRefs.filter(r=>refBy(r.id));const steps='<div class="steps">'+c.sequence.map((f,i)=>'<article class="step"><span class="number">FRAME '+(i+1)+'</span><h4>'+esc(f.headline)+'</h4>'+para(f.visual)+'<small>'+esc(f.status)+'</small></article>').join('')+'</div>';showDrawer(ideaLane(c)+' · proposed idea · '+c.id,c.title,section('What this idea should do',para(c.objective))+section('Why these references',refLinks(sourceRefs))+section('Your original adaptation',para(c.originalAdaptation))+section('Visual sequence',steps)+detail('Production brief',para(c.productionBrief))+detail('Platform hooks and video adaptations',para(c.copyHooks)+para(c.platformCuts))+detail('Evidence and release checks',para(c.assetTruth)+para(c.releaseGate)+para(c.measurement))+(c.reuseFrom?.length?section('Existing proposed post families',relatedLinks(c.reuseFrom.map(postBy).filter(Boolean),'post')):'')+(ideaLane(c)==='Spices'?'<p class="evidence-warning">Spices brand name and product range remain unconfirmed.</p>':''));return{ideaId:id,readOnly:true};}
function captionContent(p){return'<div class="caption-tabs" aria-label="Caption platform">'+['linkedin','instagram','facebook'].map(x=>'<button data-caption="'+x+'" aria-pressed="'+(x===captionPlatform)+'">'+x[0].toUpperCase()+x.slice(1)+'</button>').join('')+'</div><label for="caption-text" class="sr-only">'+captionPlatform+' draft caption</label><textarea id="caption-text" class="caption-text" readonly>'+esc(p.copy[captionPlatform])+'</textarea><div class="drawer-actions"><button class="secondary" id="copy-caption">Copy caption</button><button class="secondary" id="download-brief">Download post brief</button></div><p class="caption-note">Read-only draft. Copying or downloading does not publish or schedule it.</p>';}
function wireCaption(){const p=postBy(postId);all('[data-caption]').forEach(b=>b.addEventListener('click',()=>{captionPlatform=b.dataset.caption;$('#caption-region').innerHTML=captionContent(p);wireCaption();}));$('#copy-caption').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(p.copy[captionPlatform]);toast('Draft caption copied.');}catch{$('#caption-text').focus();$('#caption-text').select();toast('Copy is unavailable here. The caption is selected for manual copying.');}});$('#download-brief').addEventListener('click',()=>{const content=p.title+'\nProposed '+p.date+' · '+p.primaryFormat+'\n\n'+Object.entries(p.copy).map(([k,v])=>k.toUpperCase()+'\n'+v).join('\n\n')+'\n\nSOURCES\n'+p.sourceRefs.map(r=>r.brand+'\n'+r.url).join('\n\n')+'\n\nPRODUCTION\n'+text(p.video||p.carousel)+'\n\nRELEASE CHECK\n'+p.releaseGate;const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='roza-'+p.id.toLowerCase()+'-draft-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
function openPost(id){const p=postBy(id);if(!p)throw Error('Unknown proposed post');postId=id;captionPlatform='linkedin';let frames='';if(p.carousel?.length)frames=section('Carousel / gallery frames','<div class="steps">'+p.carousel.map(f=>'<article class="step"><span class="number">FRAME '+f.number+'</span><h4>'+esc(f.title)+'</h4>'+para(f.body)+'<small>'+esc(f.layout)+'</small></article>').join('')+'</div>');let shots='';if(p.video?.shots?.length)shots=detail('Video shot list · '+p.video.duration,para(p.video.voiceover)+'<div class="steps">'+p.video.shots.map(s=>'<article class="step"><span class="number">'+esc(s.seconds)+' SEC</span><h4>'+esc(s.onScreen)+'</h4>'+para(s.visual)+'<small>'+esc(s.audio)+'</small></article>').join('')+'</div>');showDrawer('Proposed '+p.date+' · '+p.primaryFormat+' · '+p.id,p.title,'<p class="evidence-warning">Draft for review. The date is a proposal; this post has not been approved or scheduled.</p>'+section('Purpose',para(p.objective)+para(p.adaptation))+section('References behind this post',refLinks(p.sourceRefs.filter(r=>refBy(r.id))))+'<section class="detail-section"><h3>Platform-ready draft copy</h3><div id="caption-region">'+captionContent(p)+'</div></section>'+frames+shots+detail('Assets and release checks',para(p.assets)+para(p.evidenceStatus)+para(p.releaseGate)+para(p.fallback)));wireCaption();return{postId:id,status:'proposed draft'};}
function bindOpeners(root){root.querySelectorAll('[data-open-ref]').forEach(b=>b.addEventListener('click',()=>openReference(b.dataset.openRef)));root.querySelectorAll('[data-open-idea]').forEach(b=>b.addEventListener('click',()=>openIdea(b.dataset.openIdea)));root.querySelectorAll('[data-open-post]').forEach(b=>b.addEventListener('click',()=>openPost(b.dataset.openPost)));}
function openGuidance(){showDrawer('Official guidance · dated sources','What the platforms actually say',E.guidance.sources.map(g=>'<article class="guidance-card"><span class="overline">'+esc(g.platform)+'</span><h3>'+esc(g.title)+'</h3><small>'+esc(g.publisher+' · '+(g.date||g.date_displayed))+'</small>'+section('Supported by this source',para(g.supports))+section('Useful application',para(g.application))+detail('What it does not prove',para(g.does_not_support))+'<a href="'+safeUrl(g.url)+'" target="_blank" rel="noopener noreferrer">Read the official source</a></article>').join('')+'<p class="evidence-warning">No hidden ranking weights or guaranteed reach are established. A recent post is not automatically a trend.</p>');}
all('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));all('[data-plan-mode]').forEach(b=>b.addEventListener('click',()=>{planMode=b.dataset.planMode;all('[data-plan-mode]').forEach(x=>x.setAttribute('aria-pressed',x===b?'true':'false'));render();}));['search','brand-filter','platform-filter','evidence-filter','format-filter'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));$('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});$('#guidance-button').addEventListener('click',openGuidance);$('#evidence-filter').innerHTML='<option value="captured">Visual available ('+L.records.filter(r=>r.images.length).length+')</option><option value="textonly">Text only ('+L.records.filter(r=>!r.images.length).length+')</option><option value="all">All references ('+L.records.length+')</option><option value="live">Public page inspected</option><option value="cached">Cached text</option><option value="snippet">Search snippet only</option>';options();render();window.ROZA_REFERENCE_LIBRARY={setView,openReference,openIdea,openPost,openGuidance,selected};
})();
